name: "Automated Code Review"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code_review_job:
    runs-on: ubuntu-latest

    steps:
      - name: Automated Code Review
        uses: shivendratiwari07/code_review@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_SERVICE_COOKIE: ${{ secrets.CUSTOM_SERVICE_COOKIE }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
##