name: "Automated Code Review"

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  code_review_job:
    runs-on: ubuntu-latest

    steps:
      - name: Automated Code Review
        uses: shivendratiwari07/code_review@cookies
        with:
          GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_GH_TOKEN }}
          DEX_USERNAME: ${{ secrets.DEX_USERNAME }}
          DEX_PASSWORD: ${{ secrets.DEX_PASSWORD }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
##